### ISSUE TITLE
WMF P&E Alpha tracking

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#866]
- [x] Articles can be assigned for any language / project
    - [x] GUI for choosing project and language of assignment
- [x] Article links in interface point to the correct wiki
- [x] Metrics are pulled from the respective wikis for each assignment article
- [x] Interface messages 100% available for translation (except for features that will not be used in the alpha, including the wizard, the trainings, and surveys)
- [x] Wiki Ed-only messages are marked as such
- [x] 'Find my program' button on dashboard homepage, if open course creation is enabled
- [x] Tests for multiwiki / WMF features:
    - [x] non-en course creation
    - [x] assigning cross-wiki articles
    - [x] pulling stats for cross-wiki programs
    - [x] open course creation
- [x] Documentation of multiwiki-specific features

## Stretch goals
- [ ] Fetch revisions and metrics for all enrolled users, across all wikis

**Comment by ragesoss** [comment]
We're not going to push forward the stretch goal for the alpha, because there are some significant bottlenecks in the update system that we should probably work through first.

The baseline alpha features are ready!
